### ISSUE TITLE
Clarification on authentication configuration

### ISSUE THREAD

**Issue by PhilHannent** [ewsjs/xhr#1]
Hi,

I'm creating a server service, which a variety of consumers will utilise. Some will be accessing Office 365 some will be accessing their own Exchange servers. The Office 365 is working as expected and the Exchange is failing with 401 errors. 

So looking at the documentation it seems like I need to setup either a NTLM authentication using the @ews/xhr library. The library documentation says to use:
```
import { XhrApi } from "@ewsjs/xhr";

let xhr = new XhrApi()
    .useNtlmAuthentication(credentials.userName, credentials.password);
ConfigurationApi.ConfigureXHR(xhr);
```

However, this looks like a call which is affecting the ews-javascript-api runtime, which would be for all users within that process (which would be a bad thing). I need the design to be on a per user request basis and the current documentation doesn't make that clear.

Can you clarify the situation?

Thanks
Phil

**Comment by gautamsi** [comment]
you can configure global option as well as service instance option as well. 

you can use above approach for global configuration, if you want to use per instance, try this.

```ts
import { XhrApi } from "@ewsjs/xhr";
let xhr = new XhrApi()
    .useNtlmAuthentication(credentials.userName, credentials.password);
const service = new ExchangeService(....);
service.XHRApi = xhr;
```

if you want NTLM for Global, you can use basic for specific instance with this 

```ts
import { XhrApi } from "@ewsjs/xhr";
let xhr = new XhrApi();
const service = new ExchangeService(....);
service.XHRApi = xhr;
```

**Comment by PhilHannent** [comment]
Thank you very much, that worked. I then got an error about the server TimeZone. Which I set to local and I was able to make appointments and update them.

The speed of your reply is very much appreciated.
