### ISSUE TITLE
Build fails on "no exported member 'ntlmAuthXhrApi'"

### ISSUE THREAD

**Issue by schadock29** [ewsjs/xhr#12]
On build, I get the error : 

`
node_modules/@ewsjs/xhr/dist/index.d.ts:1:10 - error TS2305: Module '"./ntlmAuthXhrApi"' has no exported member 'ntlmAuthXhrApi'.

1 export { ntlmAuthXhrApi } from "./ntlmAuthXhrApi";
`

Using version 1.4.3

Bug probably related with https://github.com/ewsjs/xhr/issues/10

**Comment by gautamsi** [comment]
Seems like it did not fix it

**Comment by oskargronqvist** [comment]
The fix was overwritten when publishing the lib.

You probably need to remove @internal from xhr/src/ntlmAuthXhrApi.ts or "stripInternal": true from xhr/tsconfig.json.

**Comment by gautamsi** [comment]
I have published another version to fix this

**Comment by oskargronqvist** [comment]
Thanks! That seems to have solved the issue for me.

**Comment by schadock29** [comment]
Version 1.4.4 solves the issue.

Thanks
