### ISSUE TITLE
Node 18 Support

### ISSUE THREAD

**Issue by tomer953** [ewsjs/xhr#13]
Hi,
We are using this package to authenticate our Exchange server with NTLM authentication
However, when upgrade from Node 16 LTS to Node 18, we are getting an error when trying to work with EWS:

`0308010c:digital envelope routines::unsupported`

```javascript
Error error 0308010c:digital envelope routines::unsupported
  at new Hash (node:internal/crypto/hash:71:19)
  at Object.createHash (node:crypto:133:10)
  at Object.createNTLMHash (...\@ewsjs\ntlm-client\lib\hash.js:77:22)
  ...
```

This occurs because an SSL hole found in Node 17 or something
https://stackoverflow.com/a/73027407/12989233

more info can be found here:
https://www.freecodecamp.org/news/error-error-0308010c-digital-envelope-routines-unsupported-node-error-solved/

I guess this package or the `ntlm-client` package need to be update in order to solve this without any workarounds.

thanks for your help

**Comment by gautamsi** [comment]
this was fixed in 3.0.0
