### ISSUE TITLE
Don't install

### ISSUE THREAD

**Issue by german-st** [ewsjs/xhr#3]
Hello @gautamsi @tobiasviehweger 
I can not install the module. I getting an error.
Tried the commands:

`npm install @ewsjs/xhr --save`
`npm install -g @ewsjs/xhr`

![image](https://user-images.githubusercontent.com/30233260/51566518-c7adbd00-1ea5-11e9-8729-773df833b561.png)

I have installed GIT for windows and registered in PATH variable.
```
C:\projects\test>git --version
git version 2.20.1.windows.1
```

**Comment by gautamsi** [comment]
It may be a machine specific issue. you may need to reinstall NPM

**Comment by german-st** [comment]
Unfortunately such a problem on 3 different machines)  All windows instances.
I do not know what else to try)

My Node.js version:
v10.15.0
npm: 6.4.1

**Comment by gautamsi** [comment]
you tell me, how can I help you. 

![image](https://user-images.githubusercontent.com/5769869/51597875-4ea07b00-1f22-11e9-82dd-606c2373035e.png)


quick search on this suggests deleting `package-lock.json` and try again

**Comment by german-st** [comment]
Thank you very much. I will try further. 
And thanks for the great module!
