### ISSUE TITLE
i cant understand from where come the problem

### ISSUE THREAD

**Issue by segvoltage** [ewsjs/xhr#5]
the install passed without any problem ,
i imported the package without any problem 
import {XhrApi} from "@ewsjs/xhr";
i made a simple submit function for test but erros below displayed , is there any solution for this
  onSubmit(){
    let xhr = new XhrApi();
    //this.router.navigate(['/dashboard']);
  }
Date: 2019-03-11T16:57:27.617Z
Hash: d80e2e8b54b871118f54
Time: 13389ms
chunk {main} main.js, main.js.map (main) 1.93 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 681 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 293 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

ERROR in node_modules/@ewsjs/xhr/src/cookieProvider.ts(7,37): error TS2307: Cannot find module 'https'.
node_modules/@ewsjs/xhr/src/ntlmAuthXhrApi.ts(6,37): error TS2307: Cannot find module 'https'.
node_modules/@ewsjs/xhr/src/ntlmAuthXhrApi.ts(7,36): error TS2307: Cannot find module 'http'.
node_modules/@ewsjs/xhr/src/ntlmAuthXhrApi.ts(9,70): error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.
node_modules/@ewsjs/xhr/src/ntlmProvider.ts(7,37): error TS2307: Cannot find module 'https'.
node_modules/@ewsjs/xhr/src/ntlmProvider.ts(9,70): error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.
node_modules/@ewsjs/xhr/src/proxySupportedXhrApi.ts(6,37): error TS2307: Cannot find module 'https'.
node_modules/@ewsjs/xhr/src/proxySupportedXhrApi.ts(7,32): error TS2307: Cannot find module 'http'.
node_modules/@ewsjs/xhr/src/xhrApi.ts(7,53): error TS2307: Cannot find module 'https'.
node_modules/@ewsjs/xhr/src/xhrApi.ts(8,32): error TS2307: Cannot find module 'http'.

**Comment by gautamsi** [comment]
are you trying this in a browser? this is only for node, does not work with browser.

**Comment by segvoltage** [comment]
thankyou @gautamsi i got my mistak
