### ISSUE TITLE
How to use Windows Integrated Authentication

### ISSUE THREAD

**Issue by privatmamtora** [ewsjs/xhr#8]
Hello thank you very much for the library.

I have managed to get everything working with NTLM Authentication.

But to avoid hardcoding username and password in my code, I was hoping to use the Windows integrated authentication.

Any chance you have a sample for that?

Thanks

**Comment by gautamsi** [comment]
unfortunately I could not find a simple library to do NTLM based integrated auth client side. There are some available in server side. I found few complex one but that only support the kerberos based integrated authentication. I have worked on Exchange Server (server side) for very long time and kerberos is not a preferred one by the majority for integrated auth in Exchange world.

**Comment by privatmamtora** [comment]
Any other recommendations to avoid putting password in code or configuration? (Basically I want to run it in an unsecured environment)
Currently the only thing I can figure is to ask for the password on start, through user input.
Or if more secrets are needed then use an encrypted store.

Basically a one time thing. (Next time process is started, the password would be required again)

**Comment by gautamsi** [comment]
well, it is like any other secret requirements, if you are running in the Azure or AWS they have secure way to pass environment variable (I read somewhere), Other way is to use reversible encryption which is guarded by permission and configurable only by the admin credential. you can limit the surface but can not eliminate it completely.
